name: SCA Scans

on:
  push:

jobs:
  SCA-Scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Sources
        uses: actions/checkout@v2
      - name: GrypeDependencyScanner(Report)
        id: scan
        uses: anchore/scan-action@v3
        with:
          path: "."
          acs-report-enable: true
          fail-build: false
      - name: Inspect Dependency SARIF Report
        run: cat ${{ steps.scan.outputs.sarif }}
